USER_REGISTRY_CONTRACT_FILE = 'user_registry_contract.sol'

USER_REGISTRY_CONTRACT_INTERFACE = 'user_registry_contract_interface.in'

USER_REGISTRY_CONTRACT_ADDRESS = ''

USER_REGISTRY_CONTRACT_NAME = 'UserRegistryContract'

CONTRACT_DEPLOYMENT_GAS = 1000000
